databases:
  - name: hamatan
    databaseName: hamatan
    user: miyazaki
    region: singapore

services:
  - type: web
    name: hamatan
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails7_sample_staginhamatan
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false