databases:
  - name: hamatan
    databaseName: hamatan
    user: hamatan_user

services:
  - type: web
    name: hamatan
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: "postgres://hamatan_user:xx7pW7zMaXCAmOeWLQQvEGlJ7qj62esU@dpg-cl12p5as1bgc73e3enjg-a.singapore-postgres.render.com/hamatan"
        fromDatabase:
          name: hamatan
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false